## What is this
This is the helpers of numpy when I learn the Udacity Data Scientist Nanodegree. Some of them have examples, some of them are just links to other people's answers. 
Hope this will help people who is new to python and numpy.

-------

### [Random seed](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.seed.html)
Seed the generator.

In [1]:
import numpy as np

print(np.random.rand(4))
print(np.random.rand(4))

[0.86761559 0.72666063 0.35099076 0.64136087]
[0.40356302 0.07810004 0.67801954 0.35649283]


In [2]:
import numpy as np

np.random.seed(1)
print(np.random.rand(4))

np.random.seed(1)
print(np.random.rand(4))

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]


------

### [Difference between numpy.array shape (R, 1) and (R,)](https://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r)

In [3]:
import util

a = np.arange(12)

util.shapePrintHelper(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------
shape: (12,)


In [4]:
# reshape it to (6, 2)
b = a.reshape(6,2)

util.shapePrintHelper(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
----------
shape: (6, 2)


In [5]:
# reshape it to (1, 12)
c = b.reshape(1, 12)
util.shapePrintHelper(c)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
----------
shape: (1, 12)


In [6]:
# will have error if reshape to a shape (x,y) that x*y !== number of element

d = c.reshape(3, 3)
util.shapePrintHelper(d)

ValueError: cannot reshape array of size 12 into shape (3,3)

-----------